apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yash-pvc
  namespace: yash 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: yash-sc