apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: yash-sc
  namespace: yash 
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  type: gp2